# Generated by Django 6.0.4 on 2026-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('imageurl', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
