# Generated by Django 6.0.4 on 2026-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_data',
            name='imageurl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
