# Generated by Django 6.0.4 on 2026-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_store_data_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_data',
            name='imageurl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
